spring:
  application:
    name: aggregator
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      # defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/
      defaultZone: http://localhost:8761/eureka/